### ISSUE TITLE
Click-to-sort headers for all tabular data

### ISSUE THREAD

**Issue by myself248** [mjgardes/seltzer#10]
See https://github.com/elplatt/seltzer/issues/206

It's silly having to pull CSVs to do something simple like that. Every header that contains sortable data should be clickable to do that. And CID should be shown so I can use it as a sort key. :)

**Comment by UnixMonky** [comment]
Pushed to prod, all tables (or at least all tables using the standard seltzer-table definition, which should be all tables but can't be guaranteed) now can be sorted by clicking on the column header to sort on.
