### ISSUE TITLE
Report: Members exiting

### ISSUE THREAD

**Issue by myself248** [mjgardes/seltzer#11]
Since we can enter arbitrary dates into date fields, this actually needs two implementations, for different purposes:

"Anyone whose plan didn't have an end-date set previously but now has one" (I would use this to figure out who to send exit-interviews to)
and
"Anyone whose plan-end-date falls within the previous x days, or current/previous calendar month" (I would use this to report who's recently stopped being a member)

Imagine someone who says "I'm going back to school at the end of august, set my plan to end then so I'm not billed after that", but this gets set back in July; if I pull the reports in mid-August I'd want them on the first list so I can ask why they're leaving while the event is fresh in their mind, but only appear on the second list when I pull the september report to talk about who's actually left. 

Either one would be better than nothing. Both would be glorious. :) 

(For purposes of this ticket, "hiatus" shouldn't count as a membership but scholarship should. I'm sorry I don't know a general way to do this.)

**Comment by UnixMonky** [comment]
The second one is somewhat simple, that's just a query against existing data.  the first request requires there be some sort of persistent state-knowledge about /when/ the end-date field was set which I don't think currently exists... I'll have to think about whether to add fields to the plan table to include modification dates, or if there's another way to do this

**Comment by mjgardes** [comment]
Can we just revise #1 to be when the end date falls within a specific
window?  I can't remember a case where we've set an end date that wasn't
within a couple days of the present with the exception of people who
departed months ago and we just now noticed.

**Comment by myself248** [comment]
Yeah, way-out end-dates are an edge-case and covering them would be nice-to-have but tending towards optional.

Specific window is the general case and I consider that a need-to-have. Thanks so much!

**Comment by UnixMonky** [comment]
Do you want fixed end-date ranges (i.e. ended in last 30, 60, 90, 180, 360 days) or a custom date (ended between ${date} and ${other date})?

**Comment by myself248** [comment]
Custom date would be more versatile. Calendar popups like the other date-entry blanks, if possible?

**Comment by UnixMonky** [comment]
report created. By default it pulls members with exit plans of "today", but there's from and to fields to specify the range to search for.

One note, it grabs all plans that end in that range, and doesn't check to see if another plan starts. I don't think this will be a big issue, but be aware.

**Comment by UnixMonky** [comment]
also, the default range it pulls is the last month's worth.
