### ISSUE TITLE
Feature request: Alternate email fields

### ISSUE THREAD

**Issue by myself248** [mjgardes/seltzer#16]
I'd like to start tightening up who's on the various members-only resources, but this is complicated by some folks having multiple email addresses. Rather than forcing them to unify (and undoing what might be useful arrangements for them), it might be kinder if the CRM could track multiple emails per user.

See #17 for how this might be used.

**Comment by UnixMonky** [comment]
This is part of a larger user profile overhaul that's been rolling around my thoughts for a while. What would an acceptable number of emails to store be? Two (primary and alternate). Seventeen (primary and 16 alternates)? I think if we're trying to correlate alternate emails with other data a text field of 'all alternate emails' would be insufficient and cause additional parsing issues.

**Comment by UnixMonky** [comment]
Merged into issue #1
