### ISSUE TITLE
Feature request: Email correlation

### ISSUE THREAD

**Issue by myself248** [mjgardes/seltzer#17]
So, there doesn't seem to be a good API for Google Groups, but I can "export members" and it gives me a CSV, which is useful. I'd love to be able to upload this (or, three of these, from i3detroit, i3detroit-public, and i3detroit-announce) and then somehow view the members list in the CRM and have it show all the folks who actually appear on the lists, and who don't. 

I have a feeling that a lot of people use different emails in the CRM versus Groups, and implementing #16 would make it possible to start tracking those alternates and reducing the discrepancies until they represent only the true unknowns, at which time we can start handling them individually.

**Comment by myself248** [comment]
I imagine the view having a column for each group, a row per user, and the data in each cell being their subscription status (none, digest, individual email, as indicated in the groups export CSV) or "no match found".

**Comment by UnixMonky** [comment]
This will probably be delayed until after the groups are migrated to groups-for-orgs, as the groups-for-plebians we use now doesn't have an API that we can use to pull data from.

**Comment by UnixMonky** [comment]
Merged into issue #1
