### ISSUE TITLE
Impossible to create a new user record without a plan

### ISSUE THREAD

**Issue by myself248** [mjgardes/seltzer#19]
This used to be a feature but now it's a bug -- in the new membership process, we're creating CRM records earlier in the joining process, before they actually have a plan, which gets added later. 

Except I can't seem to do that. The "add member" function inherently creates a plan entry. Could it not?

**Comment by UnixMonky** [comment]
Created a new plan called "Onboarding" to mange this, so that there's not any members with no plan.  Working on adding reports to list all onboarding members, and updating the member graph

**Comment by UnixMonky** [comment]
Member graph updated, change has been pushed to production.

**Comment by myself248** [comment]
You're all amazing. Closing!
