### ISSUE TITLE
Reports Leaking data when not logged in

### ISSUE THREAD

**Issue by Gansemarsch** [mjgardes/seltzer#21]
A url like https://www.i3detroit.org/crm/index.php?q=reports&name=$report_that_exists will actually run the report and list the result even if the user is not logged in. This flaw works with all of the reports in the i3 CRM. I verified using a computer that has never logged in to the CRM to check.

**Comment by Gansemarsch** [comment]
I should also note that the url returns that a report does not exist if it does not

**Comment by UnixMonky** [comment]
Working on this now.

**Comment by UnixMonky** [comment]
Fix implemnted and pushed to prod branch.
