### ISSUE TITLE
Request: Update to the CRM

### ISSUE THREAD

**Issue by Dudeology** [mjgardes/seltzer#28]
I am suggesting an edit to the CRM to add a section/box/highlight that will annotate the preferred communication method of that member.  Thanks

**Comment by UnixMonky** [comment]
This is minor, but I might be able to do this along with the other requests for more user data fields

**Comment by UnixMonky** [comment]
updated the title to be more reflective of the request.

**Comment by UnixMonky** [comment]
Merged into issue #1
