### ISSUE TITLE
feature request: storage plot assignment

### ISSUE THREAD

**Issue by abzman** [mjgardes/seltzer#30]
What I want is to have an extension to the CRM that allows people to pick member storage spots, then the wiki storage spot page can be populated by that.  It would also allow for other reservations of spots like 'wood shop storage' or 'n2d2' through an administrative menu, but to edit the wiki page the members would be directed to log into the CRM and pick a spot that's free.  
This makes the storage cleanout basically completely automated except for the 'boots on the ground' to actually migrate stuff into the dumpster
and allows for things like 'fire e-mail that you need to empty your storage plot' when a plan ends
It helps enforce 'one spot per member'
and would allow for things like 'if you go to reserve a spot and someone's already squatting in it, fire off an e-mail that the contents have been moved to the lost and found' or something
we could start and end spots like we do plans and keys

**Comment by UnixMonky** [comment]
Initial attempt complete. Please check the dev instance and verify if this is what you want.

**Comment by UnixMonky** [comment]
This is live now and being QA tested
