### ISSUE TITLE
key_view permission allows key editing

### ISSUE THREAD

**Issue by mjgardes** [mjgardes/seltzer#32]
It would seem that users with key_view can edit keys.  I think that should be restricted to key_edit.

**Comment by UnixMonky** [comment]
There's no roles that have key_view that don't also have key_edit, so as things are currently configured anyone with view access will naturally have edit access also. Is there a use case for someone to be able to view keys but not edit them?

**Comment by myself248** [comment]
We've talked about a way for remote things to query whether a key is valid. Would that thing's permissions be unrelated to the CRM users' permissions?

**Comment by mjgardes** [comment]
Do said remote things really need to log in to the web interface, or would they be happy with a daily or hourly or minutely CSV export of valid keys?

**Comment by UnixMonky** [comment]
There's not currently a use case for a warm user (as opposed to a digital gizmochi) to need to view keys without being able to edit. As gizmochis will be using the API, I'm closing this as 'not a thing to do'. We can reopen if circumstances change.
