### ISSUE TITLE
Key NoPlan report returns erroneous data

### ISSUE THREAD

**Issue by myself248** [mjgardes/seltzer#37]
See https://i3detroit.slack.com/archives/C0JUZURDW/p1513014872000499

**Comment by UnixMonky** [comment]
I read through the slack archives, and I don't understand what this is reporting incorrectly. It looks to me like it's showing everyone who has a key but not a valid plan. Can I get clarification on this issue? (preferably with a specific user that I can reference)

**Comment by myself248** [comment]
Looks to be behaving normally now. When that was opened, it was showing like 200 records, not the 40 it shows now. No idea what changed, sorry.

**Comment by UnixMonky** [comment]
In the interest of cleaning the cruft, I'm going to close this. Please reopen if it happens again.

**Comment by UnixMonky** [comment]
Found a sample of incorrect reporting (thanks terry!). Beth (cid 470) is hiatus with key and not on report.

**Comment by UnixMonky** [comment]
Updates were done a while ago, but I pushed to prod this afternoon.
