### ISSUE TITLE
Report: Users who have no plan entries at all, or whose plans all exist in the future. 

### ISSUE THREAD

**Issue by myself248** [mjgardes/seltzer#4]
This is another data anomaly I'd like to be able to keep an eye on.

**Comment by UnixMonky** [comment]
At the risk of creating more work, I'm contemplating this in the context of a "reports" tab rewrite, where we can add new reports as needs warrant. is there a better place to collect the various things people need to get from the CRM?

**Comment by UnixMonky** [comment]
Added contacts with no plan details as a report in the newly rewritten reports module. I'll look into the "plans starting in the future" option next. Do we know for sure that such a thing currently exists?

**Comment by myself248** [comment]
We don't, but you could do that with Testy McTesterson. ISTR it came up once where a date had been entered incorrectly, and someone wasn't being billed because the CRM correctly saw that their plan wasn't active in the present. In general I'm looking for all sorts of anomalies to be reported.

**Comment by UnixMonky** [comment]
apparently I never pushed the report up to prod, it's there now
