### ISSUE TITLE
Username displayed in Slack module may or may not be accurate.

### ISSUE THREAD

**Issue by myself248** [mjgardes/seltzer#47]
Look at i3detroit CID 655 or 672, for instance. The username on the member's main page is not necessarily the same as the username on the Services tab under Slack, which is fine, but furthermore that's not necessarily the same as their actual Slack username. This latter discrepancy is a bug. 

Currently there's no way to correlate a CRM user to a Slack user. Given that one creates the other, I feel like there should be.

**Comment by UnixMonky** [comment]
Okay, I see what's going on. CRM is correctly reporting the "name" as returned by Slack:
```
    [302]=>
    array(19) {
      ---8<---
      ["name"]=>
      string(12) "peterabotros"
```
however, that is apparently not the same as "display name". I'll look into updating and returning a better value.

**Comment by UnixMonky** [comment]
fixed in prod now.
