### ISSUE TITLE
Can't delete plans from member accounts

### ISSUE THREAD

**Issue by JodyRaiford** [mjgardes/seltzer#54]
I can edit the members' Plan, but I can't delete ones that are wrong. When I hit the Delete button, I get the correct message asking to confirm the deletion, but when I confirm, the browser goes to "https://www.i3detroit.org/crm/index.php?q=" and hangs.
When I next open any CRM page, I get the message: "No such data type: membership" at the top of the page, in addition to the information I expect to be on that page.

**Comment by JodyRaiford** [comment]
If it is, then someone removed the functionality without removing the button.
As it is, I have just been editing the plans into sequential Hiatuses, since I can't just delete wrong plans.

I guess we can update this request to "If I can't delete plans, can we get rid of the non-functional delete button?"

**Comment by rumplestilzken** [comment]
I fixed this in code that was merged into mtfurlan's feat/containerize branch.
The delete works fine, it just shows an error message talking about a member_plan.
I used existing code to pull the member_plan table into the theme.

**Comment by rumplestilzken** [comment]
I can make the change again in your branch of production, if that will make things easier?

**Comment by mjgardes** [comment]
That would be helpful.

**Comment by rumplestilzken** [comment]
#60 PR

**Comment by rumplestilzken** [comment]
Ok, so the fix i put in was valid, but for a different test case, i was able to reproduce the issue reported where the page hangs. I'm looking into it.

**Comment by rumplestilzken** [comment]
Fixed as of PR #62
