### ISSUE TITLE
Member filters are not working properly

### ISSUE THREAD

**Issue by UnixMonky** [mjgardes/seltzer#63]
The filters on the member chart are not filtering correctly. They are hardcoded to plan.pid and need to be adjusted to be more flexible for future plan changes.

**Comment by rumplestilzken** [comment]
I will take a look at this later today.

Could you take a screen shot of what you mean by "member chart"? Is this it? 
![image](https://github.com/mjgardes/seltzer/assets/3538006/de5276ed-89b7-4cd9-aade-0252f814b8e2)
![image](https://github.com/mjgardes/seltzer/assets/3538006/961a9cdf-95d9-4a72-9a29-3822a9424ee3)

How do you see them being more flexible? What was your vision for making it work correctly?

**Comment by UnixMonky** [comment]
I’ve already fixed it, just putting the PR together now and wanted the reference for it

**Comment by rumplestilzken** [comment]
Ok cool. Thanks.
