### ISSUE TITLE
Feature request: Arbitrary fields, notes field, member field, checkbox field

### ISSUE THREAD

**Issue by myself248** [mjgardes/seltzer#9]
Please turn Seltzer into Excel? Just an itty bitty bit?

I'd love to be able to create text fields associated with each contact, edit them within the usual member-record-edit function (or, gloriously, in some sort of bulk-edit or export-edit-import workflow), and potentially tie future features to their contents.

Some text fields I could imagine using:
- Where heard about i3?
- Why leaving?
- street address (see https://github.com/elplatt/seltzer/issues/352 for why)

Member-choice fields:
- If you heard about i3 from an existing member, who? (and then build a tree graph!)

Checkbox field:
- emergency contact verified 2016 data audit
- never send automated emails to this person (so we wouldn't need bogus email data)
- okay with geoplaced address appearing on member density maps

**Comment by Gansemarsch** [comment]
I would like to second the arbitrary fields request. Having a slack name box would be super useful when distinguishing non-members/former-members from members in digital land.

**Comment by chris18890** [comment]
@myself248 In Seltzer 0.5.0 there is the user-meta module, which allows you to assign arbitrarty tags toa  user, would this fulfill some of your requiremetns? #361 has also now happened, meaning that if you wanted to hack member it's significantly easier to do so :)

**Comment by UnixMonky** [comment]
Merged into issue #1
